accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns =[
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('registration/', views.Registration.as_view(), name='registration'),  # 追加
    path('registration/complete', views.RegistrationComp.as_view(), name='registration_complete'),  # 追加
    
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('company/',views.CompanyList.as_view(),name='company_list'),
    path('company/create/',views.CompanyCreate.as_view(),name='company_create'),
    path('company/detail/<int:pk>',views.CompanyDetail.as_view(),name='company_detail'),

    path('sanalysis/',views.SAnalysisList.as_view(),name='sanalysis_list'),
    path('sanalysis/create/',views.SAnalysisCreate.as_view(),name='sanalysis_create'),
    path('sanalysis/detail/<int:pk>',views.SAnalysisDetail.as_view(),name='sanalysis_detail'),

    path('ianalysis/',views.IAnalysisList.as_view(),name='ianalysis_list'),
    path('ianalysis/create/',views.IAnalysisCreate.as_view(),name='ianalysis_create'),
    path('ianalysis/detail/<int:pk>',views.IAnalysisDetail.as_view(),name='ianalysis_detail'),


    path('es/',views.ESList.as_view(),name='es_list'),
    path('es/create/',views.ESCreate.as_view(),name='es_create'),

    path('intern/',views.InternList.as_view(),name='intern_list'),
]

shusapo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('support/',include('support.urls')),
    path('', include('accounts.urls')), 
    path('board/',include('board.urls')),
]

support/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="support"

urlpatterns = [
    path('top/', views.Top.as_view(), name='top'),
    path('home/',views.home,name='home'),
    path('home/contact',views.contact,name='contact'),
    path('top/comment_create',views.CommentCreate.as_view(),name='comment_create'),

]

support/models.py
from django.db import models
from django.contrib.auth import get_user_model


user = get_user_model()

class Comment(models.Model):
    post_user = models.ForeignKey(user, on_delete=models.PROTECT)
    main = models.CharField(max_length=30)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.main+"("+str(self.post_user)+")"

    class Meta:
        ordering = ('-date',)
        

support/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('main',)

support/views.py
from django.shortcuts import render
from django.views import generic
from . import models
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
# Create your views here.

class Top(generic.TemplateView):
    template_name = 'support/top.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        comments = models.Comment.objects.all()
        context['comments'] = comments
        return context


def home(request):
    return render(request, 'support/home.html') 


def contact(request):
    return render(request, 'support/contact.html') 


class CommentCreate(generic.FormView,LoginRequiredMixin):
    form_class = forms.CommentForm
    template_name ="support/comment_create.html"
    success_url = reverse_lazy('support:top')
    
    def form_valid(self, form):
        qryset =  form.save(commit=False)
        qryset.post_user=self.request.user
        qryset.save()
        return super().form_valid(form)

templates/support/comment_create.html
{% extends 'support/base.html' %}

{% block content %}

<div class="content-wrapper">
    <section class="content-header">
        <h1 class="dash">ダッシュボード</h1>
        <br>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
            <li class="active">ダッシュボード</li>
        </ol>
    </section>
    <section class="content">
      <div class="row">
        <!-- <p>{{ post.title }}</p> -->
        <form action="" method="POST">
            <table class="table">
              {{ form.as_p }}
            </table>
            <button type="submit" class="btn btn-primary">送信</button>
            {% csrf_token %}
        </form>
  
      </div>
      <div class="row">
          <section class="col-lg-7 connectedSortable"></section>
      </div>
  </section>
{% endblock %}

templates/support/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'https://unpkg.com/ress/dist/ress.min.css' %}">
    <link rel="stylesheet" href="{% static 'original/css/stylecontact.css' %}">
    <link rel="icon" href="{% static 'original/images/favpng.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:300" rel="stylesheet">

</head>
<body>
    <header class="page-header wrapper">
        <h1 ><a class="shusapo-title" href="{% url 'support:home' %}">𝕾𝖍𝖚𝖘𝖆𝖕𝖔</a></h1>
        <nav>
            <ul class="main-nav">
                <li><a class="contact" href="{% url 'support:contact' %}">Contact</a></li>
            </ul>
        </nav>
    </header>
      
    <svg viewBox="0 0 3387 1270">
        <path id="planePath" class="planePath" d="M-226 626c439,4 636,-213 934,-225 755,-31 602,769 1334,658 562,-86 668,-698 266,-908 -401,-210 -893,189 -632,630 260,441 747,121 1051,91 360,-36 889,179 889,179" />
        <g id="plane">
          <polygon class="fil1" points="-141,-10 199,0 -198,-72 -188,-61 -171,-57 -184,-57 " />
          <polygon class="fil2" points="199,0 -141,-10 -163,63 -123,9 " />
          <polygon class="fil3" points="-95,39 -113,32 -123,9 -163,63 -105,53 -108,45 -87,48 -90,45 -103,41 -94,41 " />
          <path class="fil4" d="M-87 48l-21 -3 3 8 19 -4 -1 -1zm-26 -16l18 7 -2 -1 32 -7 -29 1 11 -4 -24 -1 -16 -18 10 23zm10 9l13 4 -4 -4 -9 0z" />
          <polygon class="fil1" points="-83,28 -94,32 -65,31 -97,38 -86,49 -67,70 199,0 -123,9 -107,27 " />
        </g>
        <!-- Define the motion path animation -->
        <animateMotion xlink:href="#plane" dur="5s" repeatCount="indefinite" rotate="auto">
          <mpath xlink:href="#planePath" />
        </animateMotion> 
    
    </svg>

    <div>
        <form id="contact">
            <div class="container">
              <div class="head">
                <h2>Contact Us</h2>
              </div>
              <input type="text" name="name" placeholder="Name" /><br />
              <input  type="email" name="email" placeholder="Email" /><br />
              <textarea type="text" name="message" placeholder="Message"></textarea><br />
              <div class="message">Message Sent</div>
              <button id="submit" type="submit">
                Send!
              </button>
            </div>
          </form>
    </div>

    <footer>
        <div>
            <p><small>&copy;2021/03/11 mahiro</small></p>
        </div>
    </footer>
    
</body>
</html>

templates/support/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'https://unpkg.com/ress/dist/ress.min.css' %}">
    <link rel="stylesheet" href="{% static 'original/css/stylehome.css' %}">
    <link rel="icon" href="{% static 'original/images/favpng.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:300" rel="stylesheet">

</head>
<body>
    <header class="page-header wrapper">
  

      
        <h1 ><a class="shusapo-title" href="{% url 'support:home' %}">𝕾𝖍𝖚𝖘𝖆𝖕𝖔</a></h1>
        <nav>
            <ul class="main-nav">
                <li>
                  <a  href="{% url 'support:contact' %}">
                    <button>CONTACT</button>
                  </a>
                </li>
            </ul>
        </nav>
        
    </header>


    <div class="bg"></div>
    <div class="bg bg2"></div>
    <div class="bg bg3"></div>
    <div class="content">
      <h1 class="oshatitle">Support Your <br> Job Hunting.</h1>
      <div>
        <p>今すぐ無料で登録して就活を始めよう</p><br>
        <div class="buttons ">
            <a href="{% url 'accounts:registration' %}" class="button">new account</a>
            <a href="{% url 'accounts:login' %}" class="button">login</a>
        </div>
        
      </div>
    </div>
    
    
</body>
</html>

templates/support/top.html
{% extends './base.html' %}
{% block content %}

<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  
  <!-- ============================== ここから以下を追加 ============================== -->
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1 class="dash">ダッシュボード</h1>
    <br>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
        <li class="active">ダッシュボード</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row" id="mainmenu">
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h4>Company</h4>
                    <p>会社一覧</p>
                </div>
                <div class="icon">
                    <i class="ion ion-android-share"></i>
                </div>
                <a href="{% url 'board:company_list' %}" class="small-box-footer">会社一覧画面を見る <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h4>Internship</h4>
                    <p>インターンシップ情報</p>
                </div>
                <div class="icon">
                    <i class="ion ion-android-share"></i>
                </div>
                <a href="{% url 'board:intern_list' %}" class="small-box-footer">インターンシップ情報を見る <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-green">
                <div class="inner">
                    <h4>Self Analysis </h4>
                    <p>自己分析</p>
                </div>
                <div class="icon">
                    <i class="ion ion-document"></i>
                </div>
                <a href="{% url 'board:sanalysis_list' %}" class="small-box-footer">みんなの自己分析を見る <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-red">
                <div class="inner">
                    <h4>Industry Eesearch</h4>
                    <p>業界研究</p>
                </div>
                <div class="icon">
                    <i class="ion ion-document"></i>
                </div>
                <a href="{% url 'board:ianalysis_list' %}" class="small-box-footer">業界研究情報を見る <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-blue">
                <div class="inner">
                    <h4>Entry Sheet</h4>
                    <p>エントリーシート</p>
                </div>
                <div class="icon">
                    <i class="ion ion-document"></i>
                </div>
                <a href="{% url 'board:es_list' %}" class="small-box-footer">自分のESを確認する <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
    </div>

    <div class="calen-comment">
        
        <div class="minkome" id="comment">
            <h4>みんなの一言コメント一覧</h4>
            <p>
                投稿日時(↑最新 ↓過去)　
                <input  class="btn btn-primary" type="button" onclick="location.reload();" value="更新" />
                <a  href="{% url 'support:comment_create' %}" class="btn btn-success">新規追加</a>
            </p>
            {% for com in comments %}
            <div class="comlist">
                <p style="font-size: 20px;">{{com.main}}</p>
                <p>(ユーザー名: {{com.post_user}} )</p>
                <p>投稿日時: {{com.date}} </p>
            
            </div>
            {% endfor %}
            
        </div>

        <div class="calen" id="calendar">
            <h2>Calendar</h2>
            <iframe src="https://calendar.google.com/calendar/embed?height=400&amp;wkst=1&amp;bgcolor=%23B39DDB&amp;ctz=Asia%2FTokyo&amp;src=amEuamFwYW5lc2UjaG9saWRheUBncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20&amp;color=%230B8043&amp;showTitle=0&amp;showNav=1&amp;showDate=1&amp;showTabs=0&amp;showPrint=0&amp;showCalendars=0" style="border:solid 1px #777" width="250" height="400" frameborder="0" scrolling="no"></iframe>
        </div>
    </div>

    <div class="row">
        <section class="col-lg-7 connectedSortable"></section>
    </div>
</section>

</div>

{% endblock content %}