board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('company/',views.CompanyList.as_view(),name='company_list'),
    path('company/create/',views.CompanyCreate.as_view(),name='company_create'),
    path('company/detail/<int:pk>',views.CompanyDetail.as_view(),name='company_detail'),

    path('sanalysis/',views.SAnalysisList.as_view(),name='sanalysis_list'),
    path('sanalysis/create/',views.SAnalysisCreate.as_view(),name='sanalysis_create'),
    path('sanalysis/detail/<int:pk>',views.SAnalysisDetail.as_view(),name='sanalysis_detail'),

    path('ianalysis/',views.IAnalysisList.as_view(),name='ianalysis_list'),
    path('ianalysis/create/',views.IAnalysisCreate.as_view(),name='ianalysis_create'),
    path('ianalysis/detail/<int:pk>',views.IAnalysisDetail.as_view(),name='ianalysis_detail'),


    path('es/',views.ESList.as_view(),name='es_list'),
    path('es/create/',views.ESCreate.as_view(),name='es_create'),

    path('intern/',views.InternList.as_view(),name='intern_list'),
]

shusapo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('support/',include('support.urls')),
    path('', include('accounts.urls')), 
    path('board/',include('board.urls')),
]

support/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="support"

urlpatterns = [
    path('top/', views.Top.as_view(), name='top'),
    path('home/',views.home,name='home'),
    path('home/contact',views.contact,name='contact'),
    path('top/comment_create',views.CommentCreate.as_view(),name='comment_create'),

]

board/models.py
from django.db import models
from django.contrib.auth.models import (
    PermissionsMixin, AbstractBaseUser
)
# Create your models here.
from django.contrib.auth import get_user_model


user = get_user_model()

# Create your views here.

# class User(AbstractBaseUser, PermissionsMixin):
#     user_name = models.CharField(max_length=30,unique=True)


class Company(models.Model):
    post_user = models.ForeignKey(user, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    comment = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name+"("+str(self.post_user)+")"

    class Meta:
        ordering = ('-date',)


class SAnalysis(models.Model):
    post_user = models.ForeignKey(user, on_delete=models.PROTECT)
    title = models.CharField(max_length=100)
    comment = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title+"("+str(self.post_user)+")"

    class Meta:
        ordering = ('-date',)




class IAnalysis(models.Model):
    post_user = models.ForeignKey(user, on_delete=models.PROTECT)
    title = models.CharField(max_length=100)
    comment = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title+"("+str(self.post_user)+")"

    class Meta:
        ordering = ('-date',)



class ES(models.Model):
    post_user = models.ForeignKey(user, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    date = models.DateField()

    def __str__(self):
        return self.name+"("+str(self.post_user)+")"

    class Meta:
        ordering = ('-date',)

board/forms.py
from .models import Company,SAnalysis,ES,IAnalysis
from django import forms


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name','comment')


class SAnalysisForm(forms.ModelForm):
    class Meta:
        model = SAnalysis
        fields = ('title','comment')

class ESForm(forms.ModelForm):
    class Meta:
        model = ES
        fields = ('name','date')

class IAnalysisForm(forms.ModelForm):
    class Meta:
        model = IAnalysis
        fields = ('title','comment')

board/views.py
from django.shortcuts import render
from django.views import generic
from .models import Company,SAnalysis,IAnalysis,ES
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models
from .forms import CompanyForm,SAnalysisForm,ESForm,IAnalysisForm
from django import forms
from django.http import HttpResponse
from django.utils import timezone
# Company

class CompanyList(generic.ListView):
    # company = Company.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')

    model = Company
    template_name = 'board/company_list.html'


class CompanyCreate(generic.FormView,LoginRequiredMixin):
    form_class = CompanyForm
    template_name ="board/company_create.html"
    success_url = reverse_lazy('board:company_list')
    
    def form_valid(self, form):
        # 入力フォームの形が正しい形で送信されてきたときに行われる処理
        qryset =  form.save(commit=False)
        qryset.post_user=self.request.user
        qryset.save()
        return super().form_valid(form)

class CompanyDetail(generic.DetailView):
    model = Company
    template_name = 'board/company_detail.html'


# SelfAnalysis

class SAnalysisList(generic.ListView):
    model = SAnalysis
    template_name = 'board/sanalysis_list.html'


class SAnalysisCreate(generic.FormView,LoginRequiredMixin):
    form_class = SAnalysisForm
    template_name ="board/sanalysis_create.html"
    success_url = reverse_lazy('board:sanalysis_list')
    
    def form_valid(self, form):
        qryset =  form.save(commit=False)
        qryset.post_user=self.request.user
        qryset.save()
        return super().form_valid(form)

class SAnalysisDetail(generic.DetailView):
    model = SAnalysis
    template_name = 'board/sanalysis_detail.html'



# ES

class ESList(generic.ListView):
    model = ES
    template_name = 'board/es_list.html'
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        es = ES.objects.all().values()
        new_es = []
        for e in es:
            if e['post_user_id'] == self.request.user.id:
                new_es.append(e)
        context['new_es'] = new_es
        return context


class ESCreate(generic.FormView,LoginRequiredMixin):
    form_class = ESForm
    template_name ="board/es_create.html"
    success_url = reverse_lazy('board:es_list')
    
    def form_valid(self, form):
        qryset =  form.save(commit=False)
        qryset.post_user=self.request.user
        qryset.save()
        return super().form_valid(form)


# intern
import requests
from bs4 import BeautifulSoup

def search():
    site = requests.get('https://job.mynavi.jp/22/pc/search/new_corps.html?OP:1&func=PCtop')
    soup = BeautifulSoup(site.text, 'html.parser')
    a_text_href = []
    for i in range(50):
        id1 = 'corpNameLink['+str(i)+']'
        id2 = 'btnEntry['+str(i)+']'

        s = soup.find(id=id1)
        s2 = soup.find(id=id2)

        text = s.text
        href = s.get('href')
        href2 = s2.get('href')
        if s:
            a_text_href.append({'text':text[:-4],'href':href,'href2':href2})
    return a_text_href


class InternList(generic.TemplateView):
    template_name = 'board/intern_list.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['a_text_href']= search()
        return context






# ianalysis


class IAnalysisList(generic.ListView):
    model = IAnalysis
    template_name = 'board/ianalysis_list.html'


class IAnalysisCreate(generic.FormView,LoginRequiredMixin):
    form_class = IAnalysisForm
    template_name ="board/ianalysis_create.html"
    success_url = reverse_lazy('board:ianalysis_list')
    
    def form_valid(self, form):
        qryset =  form.save(commit=False)
        qryset.post_user=self.request.user
        qryset.save()
        return super().form_valid(form)

class IAnalysisDetail(generic.DetailView):
    model = IAnalysis
    template_name = 'board/ianalysis_detail.html'

templates/board/company_create.html
{% extends 'support/base.html' %}

{% block content %}

<div class="content-wrapper">
    <section class="content-header">
      <h1>ダッシュボード</h1>
      <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
          <li class="active">ダッシュボード</li>
      </ol>
      <section class="content">
        <div class="row">
          <form  action="" method="POST">
            
            <div class="form-group has-feedback">
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary ">送信</button>
              {% csrf_token %}
            </div>
  
            
          </form>
  
          
    
        </div>
        <div class="row">
            <section class="col-lg-7 connectedSortable"></section>
        </div>
      </section>
    </section>
    
{% endblock %}

templates/board/company_detail.html
{% extends 'support/base.html' %}

{% block content %}


<div class="content-wrapper">
  <section class="content-header">
    <h1>ダッシュボード</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
        <li class="active">ダッシュボード</li>
    </ol>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row shousai">
        <div>
          {% if user.is_authenticated %}
          <h1>{{company.name}}</h1>
          
          <div class="box20">
            <br>
            <p style="font-size: 2rem;">
              ユーザー名: {{company.post_user}}&nbsp; 
              (投稿日時 : {{company.date}})
            </p><br>
            <p>-詳細情報-</p>
            <p>{{company.comment}}</p><br>
          </div>
          {% endif %}

        </div>
      </div>
      <a class="btn btn-primary" href="{% url 'board:company_list' %}">会社一覧に戻る</a>

    </section>
    
  </section>
  
</div>

{% endblock %}

templates/board/company_list.html
{% extends 'support/base.html' %}

{% block content %}


<div class="content-wrapper">
  <section class="content-header">
    <h1>ダッシュボード</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
        <li class="active">ダッシュボード</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row ">

        {% if user.is_authenticated %}
        <ul>
        <h2 class="shusapo-subtitle" id="company">会社一覧</h2>
        <br><p>投稿日時(↑最新 ↓過去)　
          <input class="btn btn-primary" type="button" onclick="location.reload();" value="更新" />
        </p><br>
        <p>
          このページでは過去に投稿された会社や<br>
          その会社の詳細情報を確認できます
        </p><br>
        <p>
          <a  class="btn btn-success" href="{% url 'board:company_create' %}">新規投稿</a>
          &nbsp;&nbsp;&nbsp;
          <a class="btn btn-danger" class="btn-square-or" href="{% url 'support:top' %}">Topに戻る</a>
        </p>
        
            {% for company in company_list %}
              <div class="comlist shusapo-content">
                  <p><span style="font-size: 30px;">{{company.name}}</span>&nbsp; (ユーザー名: {{company.post_user}})</p>
                  <p>投稿日時: {{company.date}} <br><a href="{% url 'board:company_detail' company.pk %}" class="comdetail">詳細はこちらから</a></p>
              </div>
            
            {% endfor %}
        </ul> 
        {% endif %}

        

    </div>
    <div class="row">
        <section class="col-lg-7 connectedSortable"></section>
    </div>

    

  </section>

</div>

{% endblock %}

templates/board/es_create.html
{% extends 'support/base.html' %}

{% block content %}

<div class="content-wrapper">
    <section class="content-header">
      <h1>ダッシュボード</h1>
      <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
          <li class="active">ダッシュボード</li>
      </ol>
      <section class="content">
        <div class="row">
          <form  action="" method="POST">
            
            <div class="form-group has-feedback">
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary ">送信</button>
              {% csrf_token %}
            </div>
          </form>
        </div>
        <div class="row">
            <section class="col-lg-7 connectedSortable"></section>
        </div>
      </section>
    </section>
    
{% endblock %}

templates/board/es_list.html
{% extends 'support/base.html' %}

{% block content %}


<div class="content-wrapper">
  <section class="content-header">
    <h1>ダッシュボード</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
        <li class="active">ダッシュボード</li>
    </ol>
  </section>
  <!-- Main content -->
  
  <section class="content">
    
    <!-- Small boxes (Stat box) -->
    <div class="row ">
      

        {% if user.is_authenticated %}
        <ul>
          <h2 class="shusapo-subtitle" id="es">{{user.get_username}}さんの登録済みESリスト</h2>
        
        <br><p>投稿日時(↑最新 ↓過去)　
          <input class="btn btn-primary" type="button" onclick="location.reload();" value="更新" />
                
        </p><br>
        <p>
          ※このページではESの期限を管理することができます。<br>
          ※ログイン中のユーザーしか閲覧できないようになってます。
        </p>

        <p>
          <a  class="btn btn-success" href="{% url 'board:es_create' %}">新規投稿</a>
          &nbsp;&nbsp;&nbsp;
          <a class="btn btn-danger"  href="{% url 'support:top' %}">Topに戻る</a>
        </p>

            {% for es in new_es %}
              <div class="comlist shusapo-content">
                  <p><span style="font-size: 30px;">{{es.name}}</span></p>
                  <p>締め切り日: {{es.date}}</p>
              </div>
            {% endfor %}
        </ul> 
        {% endif %}

        

    </div>
    <div class="row">
        <section class="col-lg-7 connectedSortable"></section>
    </div>

    

  </section>

</div>

{% endblock %}

templates/board/ianalysis_create.html
{% extends 'support/base.html' %}

{% block content %}

<div class="content-wrapper">
    <section class="content-header">
      <h1>ダッシュボード</h1>
      <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
          <li class="active">ダッシュボード</li>
      </ol>
    </section>
    <section class="content">
      <div class="row">
        <form action="" method="POST">
            <table class="table">
              {{ form.as_p }}
            </table>
            <button type="submit" class="btn btn-primary">送信</button>
            {% csrf_token %}
        </form>
  
      </div>
      <div class="row">
          <section class="col-lg-7 connectedSortable"></section>
      </div>
  </section>
{% endblock %}

templates/board/ianalysis_detail.html
{% extends 'support/base.html' %}

{% block content %}


<div class="content-wrapper">
  <section class="content-header">
    <h1>ダッシュボード</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
        <li class="active">ダッシュボード</li>
    </ol>
    <section class="content">
      <div class="row shousai">
        <div>
          {% if user.is_authenticated %}
          <h1 style="font-size: 4rem;">{{ianalysis.title}}</h1>
          
          <div class="box20">
            <br>
            <p style="font-size: 2rem;">
              ユーザー名: {{ianalysis.post_user}}&nbsp; 
              (投稿日時 : {{ianalysis.date}})
            </p>
            <br>
            <p>{{ianalysis.comment}}</p>
            <br>
          </div>
          {% endif %}
        </div>
      </div>

      <p><a class="btn btn-primary" href="{% url 'board:ianalysis_list' %}">自己分析一覧に戻る</a></p>
    </section>
  </section>
</div>

{% endblock %}

templates/board/ianalysis_list.html
{% extends 'support/base.html' %}

{% block content %}


<div class="content-wrapper">
  <section class="content-header">
    <h1>ダッシュボード</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
        <li class="active">ダッシュボード</li>
    </ol>
  </section>

  <section class="content">

    <div class="row">
      

        {% if user.is_authenticated %}
        <ul>
          <h2 class="shusapo-subtitle" style="" id="iana">みんなの業界研究一覧</h2>
          
        
        <br><p>投稿日時(↑最新 ↓過去)　
          <input class="btn btn-primary" type="button" onclick="location.reload();" value="更新" />
                
        </p><br>
        <p>
          自由に業界研究のメモを残してください！
        </p>
        <p>
          <a class="btn btn-success" href="{% url 'board:ianalysis_create' %}">新規投稿</a>
          &nbsp;&nbsp;&nbsp;
          <a class="btn btn-danger" href="{% url 'support:top' %}">Topに戻る</a>
        </p>
        
        
            {% for ianalysis in ianalysis_list %}
              <div class="comlist shusapo-content">
                  <p><span style="font-size: 30px;">{{ianalysis.title}}</span>&nbsp; (ユーザー名: {{ianalysis.post_user}})</p>
                  <p>投稿日時: {{ianalysis.date}} <br><a href="{% url 'board:ianalysis_detail' ianalysis.pk %}" class="comdetail">詳細はこちらから</a></p>
              </div>
            
            
            {% endfor %}
        </ul> 
        {% endif %}

        

    </div>
    <div class="row">
        <section class="col-lg-7 connectedSortable"></section>
    </div>

    

  </section>

</div>

{% endblock %}

templates/board/intern_list.html
{% extends 'support/base.html' %}

{% block content %}


<div class="content-wrapper">
  <section class="content-header">
    <h1>ダッシュボード</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
        <li class="active">ダッシュボード</li>
    </ol>
  </section>
  <!-- Main content -->
  
  <section class="content">
    
    <!-- Small boxes (Stat box) -->
    <div class="row ">
      

        {% if user.is_authenticated %}
        <ul>
          <h2 class="shusapo-subtitle" id="es">インターンシップ情報</h2>
        
        <br><p>投稿日時(↑最新 ↓過去)　

          <input class="btn btn-primary" type="button" onclick="location.reload();" value="更新" />
                
        </p><br>
        <p>
          最新の投稿から50件表示しています<br>
          下のリンクからインターンのエントリーが可能です<br>
          ※マイナビに登録してない方は登録が必要となります。
        </p>

        

        <p>
          <a class="btn btn-danger" href="{% url 'support:top' %}">Topに戻る</a>
        </p>

        
            {% for ath in a_text_href %}
            <p>
              <div class="int-title">
                <h3 >{{ath.text}}</h3>
                <ul class="in-li">
                  <li>
                    企業詳細情報は<a href="https://job.mynavi.jp/{{ath.href}}">こちら</a>から<br>
                  </li>
                  <li>
                    インターン応募は<a href="https://job.mynavi.jp/{{ath.href2}}">こちら</a>から
                  </li>
                </ul>
             </div>
            </p>


            <br>
            {% endfor %}
        
        

            
        </ul> 
        {% endif %}

    </div>
    <div class="row">
        <section class="col-lg-7 connectedSortable"></section>
    </div>

    

  </section>

</div>

{% endblock %}

templates/board/sanalysis_create.html
{% extends 'support/base.html' %}

{% block content %}

<div class="content-wrapper">
    <section class="content-header">
      <h1>ダッシュボード</h1>
      <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
          <li class="active">ダッシュボード</li>
      </ol>
    </section>
    <section class="content">
      <div class="row">
        <form action="" method="POST">
            <table class="table">
              {{ form.as_p }}
            </table>
            <button type="submit" class="btn btn-primary">送信</button>
            {% csrf_token %}
        </form>
  
      </div>
      <div class="row">
          <section class="col-lg-7 connectedSortable"></section>
      </div>
  </section>
{% endblock %}

templates/board/sanalysis_detail.html
{% extends 'support/base.html' %}

{% block content %}


<div class="content-wrapper">
  <section class="content-header">
    <h1>ダッシュボード</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
        <li class="active">ダッシュボード</li>
    </ol>
    
    <section class="content">
      <div class="row shousai">
        <div>
          {% if user.is_authenticated %}
          <h1 style="font-size: 4rem;">{{sanalysis.title}}</h1>
          
          <div class="box20" >
            <br>
            <p style="font-size: 2rem;">
              ユーザー名: {{sanalysis.post_user}}&nbsp; 
              (投稿日時 : {{sanalysis.date}})
            </p>
            <br>
            <p>{{sanalysis.comment}}</p>
            <br>
          </div>
          {% endif %}
        </div>
      </div>

      <p><a class="btn btn-primary" href="{% url 'board:sanalysis_list' %}">自己分析一覧に戻る</a></p>
    </section>
  </section>
</div>

{% endblock %}

templates/board/sanalysis_list.html
{% extends 'support/base.html' %}

{% block content %}


<div class="content-wrapper">
  <section class="content-header">
    <h1>ダッシュボード</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
        <li class="active">ダッシュボード</li>
    </ol>
  </section>
  <!-- Main content -->
  
  <section class="content">
    
    <!-- Small boxes (Stat box) -->
    <div class="row">
      

        {% if user.is_authenticated %}
        <ul>
          <h2 class="shusapo-subtitle" id="sana">みんなの自己分析一覧</h2>
          
        
        <br><p>投稿日時(↑最新 ↓過去)　
          <input class="btn btn-primary" type="button" onclick="location.reload();" value="更新" />
                
        </p><br>
        <p>
          自由に自己分析のメモを残してください！
        </p>
        <p>
          <a class="btn btn-success" href="{% url 'board:sanalysis_create' %}">新規投稿</a>
          &nbsp;&nbsp;&nbsp;
          <a class="btn btn-danger" href="{% url 'support:top' %}">Topに戻る</a>
        </p>
        
        
            {% for sanalysis in sanalysis_list %}
              <div class="comlist shusapo-content">
                  <p><span style="font-size: 30px;">{{sanalysis.title}}</span>&nbsp; (ユーザー名: {{sanalysis.post_user}})</p>
                  <p>投稿日時: {{sanalysis.date}} <br><a href="{% url 'board:sanalysis_detail' sanalysis.pk %}" class="comdetail">詳細はこちらから</a></p>
              </div>
            
            
            {% endfor %}
        </ul> 
        {% endif %}

        

    </div>
    <div class="row">
        <section class="col-lg-7 connectedSortable"></section>
    </div>

    

  </section>

</div>

{% endblock %}